#!/bin/bash
ssh_key='id_rsa.pub'

while getopts p:a: flag
do
    case "${flag}" in
        p) sshport=${OPTARG};;
        a) ipaddress=${OPTARG};;
    esac
done

cat ~/.ssh/$ssh_key | ssh -p $sshport root@$ipaddress "mkdir -p ~/.ssh && chmod 700 ~/.ssh && cat >> ~/.ssh/authorized_keys"